In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
#Matrix Multiplication

In [3]:
m_1 = torch.tensor([[1,2,3],
                    [4,5,6],
                    [7,8,9]
])
m_1

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [4]:
m_2 = torch.tensor([[10,22,3],
                    [42,50,6],
                    [72,8,90]
])
m_2

tensor([[10, 22,  3],
        [42, 50,  6],
        [72,  8, 90]])

In [5]:
 torch.matmul(m_1 , m_2)

tensor([[ 310,  146,  285],
        [ 682,  386,  582],
        [1054,  626,  879]])

In [6]:
#To fix tensor shape issue , use transpose

In [7]:
m_3 = torch.rand(3,2)
m_3

tensor([[0.5917, 0.1945],
        [0.2922, 0.2878],
        [0.0269, 0.0115]])

In [8]:
m_4 = torch.rand(3,2)
m_4

tensor([[0.0544, 0.9364],
        [0.0591, 0.7422],
        [0.7703, 0.1953]])

In [9]:
m_3.T , m_3.T.shape

(tensor([[0.5917, 0.2922, 0.0269],
         [0.1945, 0.2878, 0.0115]]),
 torch.Size([2, 3]))

In [10]:
torch.matmul(m_3.T , m_4)

tensor([[0.0702, 0.7762],
        [0.0364, 0.3980]])

In [11]:
torch.min(m_1) , m_1.min()

(tensor(1), tensor(1))

In [12]:
torch.max(m_2) , m_2.max()

(tensor(90), tensor(90))

In [13]:
torch.mean(m_1.type(torch.float32)) #chnage data type else error

tensor(5.)

In [14]:
torch.sum(m_1) , m_1.sum()

(tensor(45), tensor(45))

In [15]:
#index which has min/max value

In [16]:
m_1.argmin() , m_2.argmin()

(tensor(0), tensor(2))

In [17]:
m_1[0] , m_2[2]

(tensor([1, 2, 3]), tensor([72,  8, 90]))

In [18]:
m_1.reshape(1,9) #the product of the numbers in the bracket should be equal to number of elements in original matrix 

tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [19]:
m_1.reshape(9,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [20]:
#view chnages orginal matrix coz they share same memory

In [21]:
m_2

tensor([[10, 22,  3],
        [42, 50,  6],
        [72,  8, 90]])

In [22]:
z=m_2.view(1,9)
z

tensor([[10, 22,  3, 42, 50,  6, 72,  8, 90]])

In [23]:
z[:,0] =5 
z , m_2

(tensor([[ 5, 22,  3, 42, 50,  6, 72,  8, 90]]),
 tensor([[ 5, 22,  3],
         [42, 50,  6],
         [72,  8, 90]]))

In [24]:
stack_m = torch.stack([z,z,z,z], dim=0)
stack_m

tensor([[[ 5, 22,  3, 42, 50,  6, 72,  8, 90]],

        [[ 5, 22,  3, 42, 50,  6, 72,  8, 90]],

        [[ 5, 22,  3, 42, 50,  6, 72,  8, 90]],

        [[ 5, 22,  3, 42, 50,  6, 72,  8, 90]]])

In [25]:
stack_m = torch.stack([z,z,z,z], dim=2)
stack_m

tensor([[[ 5,  5,  5,  5],
         [22, 22, 22, 22],
         [ 3,  3,  3,  3],
         [42, 42, 42, 42],
         [50, 50, 50, 50],
         [ 6,  6,  6,  6],
         [72, 72, 72, 72],
         [ 8,  8,  8,  8],
         [90, 90, 90, 90]]])

In [26]:
z.squeeze() , z.squeeze().shape

(tensor([ 5, 22,  3, 42, 50,  6, 72,  8, 90]), torch.Size([9]))

In [27]:
torch.unsqueeze(z,1)

tensor([[[ 5, 22,  3, 42, 50,  6, 72,  8, 90]]])

In [28]:
img = torch.rand(size=(224,224,3))
#Permute 


img_p = img.permute(2,0,1)

img.shape #height , width ,colour

torch.Size([224, 224, 3])

In [29]:
img_p.shape #colour , height , width

torch.Size([3, 224, 224])

In [30]:
#Indexing

In [31]:
x = torch.arange(1,10).reshape(1,3,3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [32]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [36]:
x[0,0]

tensor([1, 2, 3])

In [35]:
x[0,0,0]

tensor(1)