In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
#Numpy to tensor

In [3]:
array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array)
array , tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [4]:
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [5]:
#Tensor to numpy

In [7]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor , numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [8]:
tensor = tensor + 1
tensor , numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [9]:
#Reproducbility

In [13]:
r_t_1 = torch.rand(3,4)
r_t_2 = torch.rand(3,4)
r_t_1 , r_t_2

(tensor([[0.8449, 0.6134, 0.0349, 0.4186],
         [0.2449, 0.7368, 0.5971, 0.7395],
         [0.4875, 0.4706, 0.1844, 0.4206]]),
 tensor([[0.4725, 0.7519, 0.1771, 0.9023],
         [0.3435, 0.1298, 0.6525, 0.1781],
         [0.6284, 0.8009, 0.5102, 0.1508]]))

In [14]:
r_t_1 == r_t_2

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
#Random but reproducible

In [19]:
random_seed = 42
torch.manual_seed(random_seed)
r_t_3 = torch.rand(3,4)
torch.manual_seed(random_seed)
r_t_4 = torch.rand(3,4)

r_t_3 , r_t_4

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [22]:
r_t_3 == r_t_4

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])