In [1]:
import torch
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [14]:
#vector
vector= torch.tensor([2,3])
vector

tensor([2, 3])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [10]:
#Matrix
MATRIX = torch.tensor([[1,2],
                       [6,7]])
MATRIX

tensor([[1, 2],
        [6, 7]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
MATRIX[1]

tensor([6, 7])

In [15]:
#Tensor
TENSOR= torch.tensor([[[1,2,3],
                       [5,6,7],
                       [8,9,0]
                      ]])
TENSOR

tensor([[[1, 2, 3],
         [5, 6, 7],
         [8, 9, 0]]])

In [17]:
TENSOR.ndim

3

In [18]:
TENSOR.shape

torch.Size([1, 3, 3])

In [20]:
#Random tensor

In [22]:
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1712, 0.0288, 0.4225, 0.0793],
        [0.2829, 0.7548, 0.3249, 0.9088],
        [0.0428, 0.5494, 0.8429, 0.6759]])

In [24]:
random_tensor.ndim

2

In [25]:
random_img_size_tensor = torch.rand(size=(224,224,3)) #height,width,colour(R,G,B)
random_img_size_tensor.shape , random_img_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [26]:
#Zeros and ones tensor

In [27]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [30]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [31]:
ones.dtype

torch.float32

In [32]:
#Range of tensor and tensor like

In [33]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
t_range= torch.arange(start=1,end=20,step=2)
t_range

tensor([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [36]:
t_zeros= torch.zeros_like(input=t_range)
t_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
#Tensor datatypes

In [41]:
t_1 = torch.tensor([3,4,5],
                   dtype=None , 
                  device = None,
                  requires_grad=False)
t_1.dtype

torch.int64

In [39]:
t_2 = torch.tensor([3.0,4.0,5.0])
t_2.dtype

torch.float32

In [42]:
t_3 = t_2.type(torch.float16)
t_3

tensor([3., 4., 5.], dtype=torch.float16)

In [43]:
t_1*t_2

tensor([ 9., 16., 25.])

In [44]:
#Tensor operations

In [45]:
t_4 = torch.tensor([1,2,3])
t_4

tensor([1, 2, 3])

In [51]:
t_4 + 10 , torch.add(t_4,10)

(tensor([11, 12, 13]), tensor([11, 12, 13]))

In [50]:
t_4 * 10 , torch.mul(t_4,10)

(tensor([10, 20, 30]), tensor([10, 20, 30]))

In [52]:
t_4 - 10 , torch.sub(t_4,10)

(tensor([-9, -8, -7]), tensor([-9, -8, -7]))